export const obtenerCategorias = ()=>
{
    const categorias =
        [
            {
                id:1,
                nombre:'Animales',
                image:'./assets/Categorias/Animales/animales.jpg',
                items:
                [
                    {
                        id:1,
                        nombreEsp:'vaca',
                        nombreEng:'cow',
                        imagen:'./assets/Categorias/Animales/items/vaca.jpg'
                    },
                    {
                        id:2,
                        nombreEsp:'caballo',
                        nombreEng:'horse',
                        imagen:'./assets/Categorias/Animales/items/caballo.jpg'
                    },
                    {
                        id:3,
                        nombreEsp:'perro',
                        nombreEng:'dog',
                        imagen:'./assets/Categorias/Animales/items/perro.jpg'
                    },
                    {
                        id:4,
                        nombreEsp:'Gato',
                        nombreEng:'cat',
                        imagen:'./assets/Categorias/Animales/items/gato.jpg'
                    },
                    {
                        id:5,
                        nombreEsp:'Gallina',
                        nombreEng:'chicken',
                        imagen:'./assets/Categorias/Animales/items/gallina.jpg'
                    },
                ]
            },
            {
                id:2,
                nombre:'Colores',
                image:'./assets/Categorias/Colores/colores.jpg',
                items:
                [
                    {
                        id:1,
                        nombreEsp:'Blanco',
                        nombreEng:'white',
                        imagen:'./assets/Categorias/Colores/items/blanco.jpg'
                    },
                    {
                        id:2,
                        nombreEsp:'Negro',
                        nombreEng:'black',
                        imagen:'./assets/Categorias/Colores/items/negro.jpg'
                    },
                    {
                        id:3,
                        nombreEsp:'Rojo',
                        nombreEng:'red',
                        imagen:'./assets/Categorias/Colores/items/rojo.jpg'
                    },
                    {
                        id:4,
                        nombreEsp:'Verde',
                        nombreEng:'green',
                        imagen:'./assets/Categorias/Colores/items/verde.jpg'
                    },
                    {
                        id:5,
                        nombreEsp:'Azul',
                        nombreEng:'blue',
                        imagen:'./assets/Categorias/Colores/items/azul.jpg'
                    },
                    {
                        id:6,
                        nombreEsp:'Gris',
                        nombreEng:'gray',
                        imagen:'./assets/Categorias/Colores/items/gris.jpg'
                    },
                    {
                        id:7,
                        nombreEsp:'Bordo',
                        nombreEng:'board',
                        imagen:'./assets/Categorias/Colores/items/bordo.jpg'
                    },
                    {
                        id:8,
                        nombreEsp:'Celeste',
                        nombreEng:'light blue',
                        imagen:'./assets/Categorias/Colores/items/celeste.jpg'
                    },
                    {
                        id:9,
                        nombreEsp:'Violeta',
                        nombreEng:'violet',
                        imagen:'./assets/Categorias/Colores/items/violeta.jpg'
                    },
                    {
                        id:10,
                        nombreEsp:'naranja',
                        nombreEng:'orange',
                        imagen:'./assets/Categorias/Colores/items/naranja.jpg'
                    },
                    {
                        id:10,
                        nombreEsp:'marron',
                        nombreEng:'brown',
                        imagen:'./assets/Categorias/Colores/items/marron.jpg'
                    },
                    {
                        id:11,
                        nombreEsp:'amarillo',
                        nombreEng:'yellow',
                        imagen:'./assets/Categorias/Colores/items/amarillo.jpg'
                    },
                    {
                        id:12,
                        nombreEsp:'rosa',
                        nombreEng:'pink',
                        imagen:'./assets/Categorias/Colores/items/rosado.jpg'
                    },
                ]
            },
            {
                id:3,
                nombre:'Comidas',
                image:'./assets/Categorias/Comidas/comidas.jpg',
                items:
                [
                    {
                        id:1,
                        nombreEsp:'Fideos',
                        nombreEng:'noodles',
                        imagen:'./assets/Categorias/Comidas/items/fideos.jpg'
                    },
                    {
                        id:2,
                        nombreEsp:'Bife',
                        nombreEng:'steak',
                        imagen:'./assets/Categorias/Comidas/items/bife.jpg'
                    },
                    {
                        id:3,
                        nombreEsp:'Arroz',
                        nombreEng:'rice',
                        imagen:'./assets/Categorias/Comidas/items/arroz.jpg'
                    },
                    {
                        id:4,
                        nombreEsp:'Parrillada',
                        nombreEng:'barbecue',
                        imagen:'./assets/Categorias/Comidas/items/parrillada.jpg'
                    },
                ]
            },
            {
                id:4,
                nombre:'Postres',
                image:'./assets/Categorias/Postres/postres.jpg',
                items:
                [
                    {
                        id:1,
                        nombreEsp:'Helado',
                        nombreEng:'ice cream',
                        imagen:'./assets/Categorias/Postres/items/helado.jpg'
                    },
                    {
                        id:2,
                        nombreEsp:'Torta',
                        nombreEng:'cake',
                        imagen:'./assets/Categorias/Postres/items/torta.jpg'
                    },
                    {
                        id:3,
                        nombreEsp:'gelatina',
                        nombreEng:'jelly',
                        imagen:'./assets/Categorias/Postres/items/gelatina.jpg'
                    },
                ]
            },
            {
                id:5,
                nombre:'Objetos',
                image:'./assets/Categorias/Objetos/objetos.jpg',
                items:
                [
                    {
                        id:1,
                        nombreEsp:'Espejo',
                        nombreEng:'mirror',
                        imagen:'./assets/Categorias/Objetos/items/espejo.jpg'
                    },
                    {
                        id:2,
                        nombreEsp:'Mesa',
                        nombreEng:'table',
                        imagen:'./assets/Categorias/Objetos/items/mesa.jpg'
                    },
                    {
                        id:3,
                        nombreEsp:'Silla',
                        nombreEng:'chair',
                        imagen:'./assets/Categorias/Objetos/items/silla.jpg'
                    },
                    {
                        id:4,
                        nombreEsp:'Puerta',
                        nombreEng:'door',
                        imagen:'./assets/Categorias/Objetos/items/puerta.jpg'
                    },
                ]
            },
            {
                id:6,
                nombre:'Insectos',
                image:'./assets/Categorias/Insectos/insectos.jpg',
                items:
                [
                    {
                        id:1,
                        nombreEsp:'Hormiga',
                        nombreEng:'ant',
                        imagen:'./assets/Categorias/Insectos/items/hormiga.jpg'
                    },
                    {
                        id:2,
                        nombreEsp:'Araña',
                        nombreEng:'spider',
                        imagen:'./assets/Categorias/Insectos/items/araña.jpg'
                    },
                    {
                        id:3,
                        nombreEsp:'Mosquito',
                        nombreEng:'mosquito',
                        imagen:'./assets/Categorias/Insectos/items/mosquito.jpg'
                    },
                    {
                        id:4,
                        nombreEsp:'Mosca',
                        nombreEng:'fly',
                        imagen:'./assets/Categorias/Insectos/items/mosca.jpg'
                    },
                ]
            },
            {
                id:7,
                nombre:'Transportes',
                image:'./assets/Categorias/Transportes/transportes.jpg',
                items:
                [
                    {
                        id:1,
                        nombreEsp:'Tren',
                        nombreEng:'train',
                        imagen:'./assets/Categorias/Transportes/items/tren.jpg'
                    },
                    {
                        id:2,
                        nombreEsp:'Avion',
                        nombreEng:'plane',
                        imagen:'./assets/Categorias/Transportes/items/avion.jpg'
                    },
                    {
                        id:3,
                        nombreEsp:'Taxi',
                        nombreEng:'cab',
                        imagen:'./assets/Categorias/Transportes/items/taxi.jpg'
                    },
                    /* frutas
                        verduras
                        partes del cuerpo
                        familia
                        formas
                        clima
                        
                         */
                ]
            }
        ]

    return categorias;
}